config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :spots, only: [:destroy] do
    resources :reviews, only: [:new, :create]
    resources :comments, only: [:create, :destroy]
  end

  resources :events, except: [:update] do
    member do
      post :join
      delete :cancel
    end

  end
  resources :users, only: [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :spot
  validates :note, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_spot, only: [:create, :destroy]
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.spot = @spot_occupied
    @event = @comment.spot.event
    authorize @comment
    if @comment.save
      respond_to do |format|
        format.html { redirect_to event_path(@event) }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_back(fallback_location: root_path, alert: "Comments cannot be blank. Please enter message into text field.") }
        format.js
      end
    end
  end

  def destroy
    set_comment
    @comment.destroy
    authorize @comment
    redirect_back(fallback_location: root_path, notice: "Comment deleted sucessfully!")
  end

  private

  def set_spot
    @spot_occupied = Spot.find(params[:spot_id])
  end

  def set_comment
    @comment = @spot_occupied.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:note, :spot_id)
  end
end

app/views/comments/_comments.html.erb
<div class="comment-details">
  <em><%= comment.created_at.strftime("  today at %I:%M %p") %></em>
    <% if current_user.id == comment.user.id %>
      <%= link_to spot_comment_path(@spot_occupied, comment), method: :delete do%><i class="fas fa-trash-alt"></i>
      <% end %>
    <% end %>
</div>
<div class="comment-content">
  <p><%= comment.note %></p>
</div>
<div class="comments-user-info">
  <p>-<%= comment.user.full_name %> <%= cl_image_tag comment.user.profile_photo, class: "avatar-comment" %></p>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([spot, comment], remote: true) do |f| %>
  <% if @comment.errors.any? %>
      <div class="errors-container">
    <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
    <div id="comments-form"><%= f.input :note, label: "Leave a comment for tonight's event", as: :text %></div>
    <%= f.submit "Post", class: "btn-dark-transparent"%>
<% end %>

app/views/comments/create.js.erb
function refreshForm(innerHTML) {
  const newCommentForm = document.getElementById('comments-form');
  newCommentForm.innerHTML = innerHTML;
}

function addComment(commentHTML) {
  const comments = document.getElementById('comments-display');
  comments.insertAdjacentHTML('beforeBegin', commentHTML);
}

<% if @comment.errors.any? %>
  refreshForm('<%= j render "comments/form", spot: @spot_occupied, comment: @comment %>');
<% else %>
  addComment('<%= j render "comments/comments", comment: @comment %>');
  refreshForm('<%= j render "comments/form", spot: @spot_occupied, comment: Comment.new %>');
<% end %>

app/views/comments/destroy.js.erb
destroy.js.erb