config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :spots, only: [:destroy] do
    resources :reviews, only: [:new, :create]
    resources :comments, only: [:create, :destroy]
  end

  resources :events, except: [:update] do
    member do
      post :join
      delete :cancel
    end

  end
  resources :users, only: [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
  has_many :spots, dependent: :destroy
  has_many :reviews, through: :spots
  has_many :comments, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @events = Event.where(user_id: current_user)
    @spot = Spot.find_by_id(params[:id])
    @review_events = Event.where('start_time < ?', Date.today)

    authorize @events
    @spots_to_review = current_user.spots

    @past_spots = current_user.spots.select do |spot|
    p spot.event.start_time < Date.today
    end

    @event = Event.find_by_id(params[:id])

    @future_spots = current_user.spots.reject do |spot|
    p spot.event.start_time < Date.today
    end

    @future_events = current_user.events.select do |event|
    p event.start_time >= Date.today
    end

    @past_events = current_user.events.select do |event|
    p event.start_time < Date.today
    end

    @unreviewed_spots = []

    @past_spots.select do |spot|
      if spot.review == nil
        @unreviewed_spots << spot
      end
    end

  end
end

app/views/users/show.html.erb
<div class="container">
  <div class="dashboard-container">
    <br>

    <div class="row">
      <% if @unreviewed_spots != [] %>
        <div class="col-sx-12 col-sm-12 col-md-10 col-lg-10">

          <% @unreviewed_spots.each do |spot| %>
            <div class="card-product review-notice">
              <%= image_tag(spot.event.photo) %>
              <div class="card-product-infos review-notice-infos">
                <h3><%= spot.user.full_name %>, you went to <%= link_to  spot.event.title , new_spot_review_path(spot) %> <%= (Date.today - Date.parse(spot.event.start_time.to_s)).to_i %> days ago.</h3>
                <p class="pl-0">Tell us how it went!</p>
                <%= link_to "Review Now", new_spot_review_path(spot), class:"btn-fun btn-dark-solid" %>
              </div>
            </div>
          <% end %>

        </div>
      <% end %>

      <div class="col-sx-12 col-sm-12 col-md-5 col-lg-5">
        <div class="dashboard-card mt-10">
          <h3>Upcoming Events</h3>
          <div class="dashboard-card-background">
            <%# if @spot.event.start_time == Date.today %>
              <% if @future_spots == [] %>
                <div class="event-list-options justify-content-center"><h5>You have no events!</h5></div>
                <div class="event-list-options justify-content-center"><%= link_to "Find an Event", root_path, method: :get, class:"btn-fun btn-dark-transparent" %></div>
              <% else %>
                <% @future_spots.each do |spot| %>
                  <div class="event-list">
                    <%= image_tag(spot.event.photo, class:"user-dashboard", height:"50px")%>
                    <p><%= link_to spot.event.title, event_path(spot.event.id) %></br>
                    <%= spot.event.start_time.strftime("%B %d, %Y") %> at <%= spot.event.start_time.strftime("%k:%M") %></p>
                    <div class="event-list-options">
                      <%= link_to(spot_path(spot.id), method: :delete) do %>
                        <i class="fas fa-ban"></i>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <%# end %>
          </div>
        </div>
      </div>

      <div class="col-sx-12 col-sm-12 col-md-5 col-lg-5">
        <div class="dashboard-card">
          <h3>Events I'm Hosting</h3>
          <div class="dashboard-card-background">
            <%# if @event.start_time <= Date.today %>
              <% if @future_events != []  %>
                <div class="event-list">
                  <% @future_events.each do |event| %>
                    <%= image_tag(event.photo, class:"user-dashboard", height:"50px")%>
                    <p>
                      <%= link_to event.title, event_path(event.id) %>
                      <%= event.start_time.strftime("%B %d, %Y") %> at <%= event.start_time.strftime("%k:%M") %>
                    </p>
                    <div class="event-list-options">
                      <div class="event-list-options">
                          <a href=""><i class="fas fa-ban"></i></a>
                        <%#= link_to "Cancel", spot_path(spot.id), method: :delete, class: "btn btn-cancel" %>
                        <%#= link_to "Cancel", '#', class: "btn btn-cancel" %>
                         <a href=""><i class="fas fa-pencil-alt edit"></i></a>
                      </div>
                    </div>
                  <% end %>
              <%# else %>
              <%# end %>
              </div>
            <% else %>
              <div class="event-list-options justify-content-center"><h5>Host an event!</h5></div>
              <div class="event-list-options justify-content-center"><%= link_to "Create an Event", new_event_path, method: :get, class:"btn-fun btn-dark-transparent"  %></div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sx-12 col-sm-12 col-md-5 col-lg-5">
        <div class="dashboard-card">
          <h3>Past Attended Events</h3>
          <div class="dashboard-card-background">
            <%# if @event.start_time < Date.today %>
              <% @past_spots.each do |spot| %>
                <div class="event-list">
                  <% if spot.event.photo %>
                    <%= image_tag(spot.event.photo, class:"user-dashboard", height:"50px") %>
                    <p><%= link_to spot.event.title, event_path(spot.event.id) %></br><%= spot.event.start_time.strftime("%B %d, %Y") %></p>
                  <% else %>
                    <p><%= link_to spot.event.title, event_path(spot.event.id) %></br><%= spot.event.start_time.strftime("%B %d, %Y") %></p> %>
                  <% end %>
                </div>
              <% end %>
            <%# end %>
          </div>
        </div>
      </div>

      <div class="col-sx-12 col-sm-12 col-md-5 col-lg-5">
        <div class="dashboard-card">
          <h3>Events I Have Hosted</h3>
          <div class="dashboard-card-background">
            <% @past_events.each do |event| %>
              <div class="event-list">
                <% if event.photo %>
                  <%= image_tag(event.photo, class:"user-dashboard", height:"50px")%>
                  <p><%= link_to event.title, event_path(event.id) %><br>
                  <%= event.start_time.strftime("%B %d, %Y") %> at <%= event.start_time.strftime("%k:%M") %></p>
                <% else %>
                  <p><%= link_to event.title, event_path(event.id) %><br>
                  <%= event.start_time.strftime("%B %d, %Y") %> at <%= event.start_time.strftime("%k:%M") %></p>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Grid setup with 4 tiles (2 on 2) -->
<!-- Tiles have margin between them (top/bottom & each side) -->
<!-- My Events have links to individual events -->
<!-- User can choose to cancel from dashboard tile -->
<!-- User can view and navigate to their HOSTED events in My Hosted tile-->
<!-- User can update profile information and edit profile picture -->
<!-- User can view events they attended in Past Events tile -->