config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :spots, only: [:destroy] do
    resources :reviews, only: [:new, :create]
    resources :comments, only: [:create, :destroy]
  end

  resources :events, except: [:update] do
    member do
      post :join
      delete :cancel
    end

  end
  resources :users, only: [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<!-- https://giantbomb1.cbsistatic.com/uploads/original/0/9545/2634556-stock-footage-a-group-of-friends-hang-out-on-a-rooftop-bar-at-night-and-dance-and-laugh-around-the-fireplace.jpg -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">

  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h1>TasteBudd</h1>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

        <li class="nav-item" style="margin-right: 5px;margin-top: 6px;">
          <%= link_to "Add an Event", new_event_path,  class: "btn-fun btn-light-solid" %>
        </li>
        <li class="nav-item" style="margin-right: 10px;margin-top: 6px;">
          <%= link_to "Dashboard", user_path(current_user),  class: "btn-fun btn-light-transparent-link" %>
        </li>


        <li class="nav-item dropdown">
          <% if current_user.profile_photo? %>
            <%= cl_image_tag current_user.profile_photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://image.flaticon.com/icons/svg/42/42877.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>
        <li class="nav-item" style="margin-right: 10px;">
          <%= link_to "Sign In", new_user_session_path, class: "btn-fun btn-dark-transparent"%>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "btn-fun btn-dark-solid" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_vibe_search.html.erb
        <%= form_tag(events_path, method: :get, class:"banner-search") do %>
          <div class="row justify-content-center form-group">

            <%= text_field_tag :search, params[:search], class: 'form-control banner-searchbar', placeholder: 'Enter Your Location' %>
          </div>
          <div class="row justify-content-between px-4">

                <% @vibes.each do |vibe| %>
                  <div class="d-flex justify-content-center pt-4 col-1 mx-3 p-2">
                    <div class="vibes clickable" data-vibe-id="<%= vibe.id %>">
                      <%= image_tag(vibe.icon, class:"img-clickable") %>
                      <%= radio_button_tag :vibe_id, vibe.id, (vibe.id), class:"radio_item" %>
                      <%= label_tag(vibe.id, vibe.name, class:"label_item")  %>
                    </div>
                  </div>
                <% end %>
          </div>

          <div class="row justify-content-center my-2">
            <div class="btn-home">
              <%= submit_tag 'Find Events!', name: nil, class: "btn-home btn-dark-solid" %>
            </div>
          </div>
        <% end %>