config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :spots, only: [:destroy] do
    resources :reviews, only: [:new, :create]
    resources :comments, only: [:create, :destroy]
  end

  resources :events, except: [:update] do
    member do
      post :join
      delete :cancel
    end

  end
  resources :users, only: [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  mount_uploader :photo, PhotoUploader

  belongs_to :vibe
  has_many :spots, dependent: :destroy
  has_many :attendants, through: :spots, source: :user
  belongs_to :user
  has_many :reviews, through: :spots
  has_many :comments, through: :spots
  has_one_attached :photo

  #validates :start_time, inclusion: { in: (Date.today..Date.tomorrow) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :update, :edit]

  def index
    @events = policy_scope(Event).order(created_at: :asc).geocoded
    @vibes = Vibe.all

    @location = params[:search]
    # @events = Vibe.find(params[:vibe_id]).events.near(params[:search]) if params[:vibe_id]
    # @current_vibe = Vibe.find(params[:vibe_id]).name if params[:vibe_id]
    #events = Vibe.find(params[:vibe_id]).events.near(params[:search])
    @current_vibe = Vibe.find_by(name: params[:vibe_id])
    @vibes_array = Vibe.all.map { |vibe| [vibe.name, vibe.id] }
    @vibes_array.unshift(["Select Vibe", 0])
    @events = Event.where(vibe_id: params[:vibe_id]).near(params[:search])

    if @events.present?
        @events
    else
        @events = Event.geocoded
        @response = "TasteBudd Events Around the World"
    end

    @markers = @events.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { event: event })
      }
    end
  end

  def show
    set_event
    if current_user
      @spot_occupied = @event.spots.select {|spot| spot.user_id == current_user.id}.first
      @event_user = @event.user
      @comment = Comment.new
      @comments = @event.comments
    else
      @event_user = @event.user
    end
      authorize @event
      @markers = [{ lat: @event.latitude, lng: @event.longitude }]
  end

  def new
    @event = Event.new
    authorize @event
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
    authorize @event
  end

  def update
    set_event
    redirect_to event_path(@event)
    authorize @event
  end

   def edit
    set_event
    authorize @event
  end

  def join
    set_event
    Spot.create(event: @event, user: current_user)
    redirect_to event_path(@event), notice: "You're going to this event!"
    authorize @event
  end

   def destroy
    set_event
    @event.destroy
    redirect_to user_path, notice: "Event was successfully removed"
    authorize @event
  end

  private

  def event_params
    params.require(:event).permit(:title, :address, :start_time, :description, :capacity, :vibe_id, :photo)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/views/events/_form.html.erb
<div class="container-contact100">

    <%= simple_form_for(@event) do |f| %>
      <div class="form-box">
        <div class="left">
          <%= f.input :title %>
          <div class ="date-box">
            <div class = "date-box-left">
              <%= Date.today.strftime("%b %-d, %Y") %>
            </div>
            <div class="date-box-right">
              <%= f.input :start_time, as: :string, input_html: {class: "datepicker"} %>
            </div>
          </div>
          <%= f.input :address %>
          <%= f.input :description %>
          <%= f.input :capacity %>
          <%= f.input :photo %>
        </div>
        <div class="right">
          <%= f.association :vibe, as: :radio_buttons %>
        </div>
      </div>
      <div class="button-div">
        <%= f.submit class: "btn-fun btn-dark-transparent" %>
      </div>
  <% end %>
</div>

app/views/events/_info_window.html.erb
<!-- <h2><%#= event.title %></h2>
<p><%#= event.address %></p> -->


<div class="card-map-info-window">
  <%= link_to event_path(event) do %>
    <% if event.photo == nil %>
      <%= image_tag("https://i1.wp.com/bestlifeonline.com/wp-content/uploads/2018/01/shutterstock_435402349.jpg?resize=500%2C322&ssl=1") %>
    <% else %>
      <%= image_tag(event.photo) %>
    <% end %>
  <% end %>
  <div class="card-map-info-window-infos">
    <div>
      <h2><%= link_to event.title, event_path(event) %></h2>
    </div>
     <p class="time"><strong>Starts at <%= event.start_time.strftime("%k:%M")%></strong> </br>
      <% if params[:search] != "" %>
        <%= event.distance_to(params[:search]).truncate(1) %> km away</p>
      <% end %>
      <div class ="card-map-info-window-vibe">
          <%= image_tag(event.vibe.icon) %>
          <p> <%= event.vibe.name %>  </p>
      </div>

  </div>
</div>

app/views/events/index.html.erb
<div class="events-parent">
  <div class="main-container">
    <div class="row">
      <div id="cards-box" role="tabpanel" aria-labelledby="cards-tab" class="col-xs-12 col-sm-12 col-md-8">
        <div class="row">
          <!-- search bar -->
          <div class="search-bar">
            <div class="row justify-content-center border-0 m-0">
                <%= form_tag(events_path, method: :get) do %>
                  <%= text_field_tag :search, params[:search], class: 'banner-searchbar', id: 'algolia-big', placeholder: 'Enter Your Location' %>
                  <%= select_tag(:vibe_id, options_for_select(@vibes_array, disabled: [["Select Vibe", 0]]), class:'vibe-selection') %>
                  <%= submit_tag 'Find Events', name: nil, class: "btn-fun btn-dark-solid" %>
                <% end %>
            </div>
            <!-- If no Events are found in the area -->
            <h3 style="margin-left: 17px;margin-top: 10px;"><%= @response %></h3>
          </div>

          <!-- cards -->
          <% @events.each do |event| %>
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
              <div class="card-trip">
                <%= link_to event_path(event) do %>
                  <% if event.photo == nil %>
                    <%= image_tag("https://i1.wp.com/bestlifeonline.com/wp-content/uploads/2018/01/shutterstock_435402349.jpg?resize=500%2C322&ssl=1") %>
                  <% else %>
                    <%= image_tag(event.photo) %>
                  <% end %>
                <% end %>

                <div class="card-trip-infos">
                  <div>
                    <h2><%= link_to event.title, event_path(event) %></h2>
                  </div>

                  <div class="card-trip-pricing">
                    <p> <span>Created by</span> <%= event.user.full_name %></p>
                    <div class="card-info-vibe-distance">
                      <div class ="card-info-vibe">
                        <%= image_tag(event.vibe.icon) %>
                        <p><%= event.vibe.name %></p>
                      </div>
                      <div class="card-info-distance">
                        <p class="time">Starts at <strong><%= event.start_time.strftime("%k:%M")%></strong></p>
                        <% if params[:search] != "" %>
                          <p class="distance"><%= event.distance_to(params[:search]).truncate(1) %> km away</p>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
                  <div class="card-trip-user">
                    <%= cl_image_tag event.user.profile_photo, class: "avatar-bordered" %>
                    <% event.attendants.each do |user| %>
                    <%= cl_image_tag user.profile_photo, class: "avatar-bordered" %>
                    <% end %>
                  </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <!-- map -->
      <div id="map-box" role="tabpanel" aria-labelledby="map-tab" class="col-xs-12 col-sm-12 col-md-4" >
        <div class="mapbox"
          id="map"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        >
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-9 m-auto">
      <h1 style="padding:0; text-align: center;">Add a New Event</h1>

        <%= render "form" %>

    </div>
  </div>
</div>
<div class="date-selector"></div>

app/views/events/search.html.erb
<h1>TasteBudd Events In Your Hood</h1>

<div class="container">
  <div class="row">
    <% @events.each do |event| %>
      <div class="col-sx-12 col-sm-6 col-md-4 col-lg-4">
        <div class="card-trip">
          <img src="https://source.unsplash.com/random" alt="Event image">
          <div class="card-trip-infos">
            <div>
              <h2><%= event.title %></h2>
            </div>
            <h2 class="card-trip-pricing">
              <p> By <%= event.user.full_name %> </p></h2>
              <% event.attendants.each do |user| %>
              <div class="card-trip-user avatar-bordered">
              <%= cl_image_tag(user.profile_photo) %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<!-- app/views/offers/show.html.erb -->
<% content_for :meta_title, "#{@event.title} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @event.description %>
<% content_for :meta_image, cl_image_path(@event.photo) %>

<div class="img mainbannercontainer">


<div class="container">
  <!-- <div class="main-container"> -->
    <div class="row">
      <div class="buddy-left  col-xm-12 col-md-6">
        <div class="showbannercontainer-left">
          <h1><%= @event.title %></h1>
          <p><strong>About the Event:</strong></br><%= @event.description %></p>
          <strong>Budds Going</strong>
        </div>

        <div class="card-product">
          <%= cl_image_tag @event.user.profile_photo, class: "avatar-bordered card-attend-img" %>
          <div class="card-product-infos">
            <% if @event.user.full_name != nil %>
              <h3><%= @event.user.full_name %> (creator)</h3>
            <% end %>
            <% if @event.user.birthday != nil %>
              <p><%= (Date.today - @event.user.birthday).to_i / 365 %> years old</p>
            <% end %>
            <% if @event.user.current_country != nil && @event.user.origin_country != nil %>
              <p>Lives in <%= @event.user.current_country %>, from <%= @event.user.origin_country %></p>
            <% end  %>
          </div>
        </div>

        <% @event.attendants.each do |user| %>
          <div class="card-product">
            <% if user.full_name != nil %>
              <%= cl_image_tag user.profile_photo, class: "avatar-bordered card-attend-img" %>
            <% else %>
              <%= image_tag "https://image.flaticon.com/icons/svg/42/42877.svg", class: "avatar" %>
            <% end %>
            <div class="card-product-infos">
              <% if user.full_name != nil %>
                <h3><%= user.full_name %></h3>
              <% end %>
              <% if user.birthday != nil %>
                <p><%= (Date.today - user.birthday).to_i / 365 %> years old</p>
              <% end  %>
              <% if user.current_country != nil && user.origin_country != nil %>
                <p>Lives in <%= user.current_country %>, from <%= user.origin_country %></p>
              <% end %>
            </div>
          </div>
        <% end %>

        <div class="comments">
          <% if @spot_occupied %>
            <h3>Comments</h3>
              <div class="comments-container">
              <%= render 'comments/form', spot: @spot_occupied, comment: @comment %>
            </div>
            <div id="comments-display">
              <% @event.comments.each do |comment|  %>
                <%= render 'comments/comments', comment: comment %>
              <% end %>
            </div>
            <% else %>
            <p><strong>Comments:</strong><br> Sign up for this event to communicate with other Taste Budds!</p>
          <% end %>
        </div>
      </div>

      <div class="detail-right col-xs-12 col-md-6">
        <div class="show-img-container">
          <%= cl_image_tag @event.photo, class: "show-img"  %>
          <div class="show-spots-left">
            <div style="font-weight: bold; font-size: 20px;"><%= @event.capacity - @event.attendants.count - 1 %> <%= "Spot".pluralize(@event.capacity - @event.attendants.count) %> Left!</div>
              <div class="show-button-right">
                <% if current_user == @event.user %>
                  <a href="">Edit Details</a>
                <% elsif @spot_occupied %>
                  <%= link_to "Cancel", spot_path(@spot_occupied), method: :delete, class: "btn-fun btn-dark-solid" %>
                <% else %>
                  <%= link_to "Join Event!", join_event_path(@event), method: :post, class: "btn-fun btn-dark-solid" %>
                <% end %>
            </div>
          </div>
        </div>
          <div class="details">
            <p><strong>Date and Time: </strong><br><%= @event.start_time.strftime("%B %d") %> at <%= @event.start_time.strftime("%k:%M")%></br></p>
            <p><strong>Location:</strong></br><%= @event.address %></p>
          </div>
          <div class="mapbox" id="map" style="width: 540px; height: 350px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>" ></div>
        </div>
      </div>
    </div>
  </div>
</div>